// components/ExpenseForm.tsx
﻿import React, { useEffect, useMemo, useState } from 'react';
import { Currency, Expense } from '../types';

interface ExpenseFormProps {
  members: string[];
  onAdd: (expense: Omit<Expense, 'id'>) => void;
}

const ExpenseForm: React.FC<ExpenseFormProps> = ({ members, onAdd }) => {
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState<string>('');
  const [currency, setCurrency] = useState<Currency>(Currency.JPY);
  const [paidBy, setPaidBy] = useState<string>(members[0] ?? '');
  const [splitAmong, setSplitAmong] = useState<string[]>(members);

  const all = useMemo(() => members, [members]);
  const isSingleMember = all.length === 1;

  const toggleSplit = (name: string) => {
    if (isSingleMember) return; // lock split when only one member
    setSplitAmong(prev => prev.includes(name) ? prev.filter(x => x !== name) : [...prev, name]);
  };

  const setAllMembers = () => setSplitAmong(all);
  const setOnlyPayer = () => setSplitAmong(paidBy ? [paidBy] : []);

  const reset = () => {
    setDescription('');
    setAmount('');
    setCurrency(Currency.JPY);
    setPaidBy(all[0] ?? '');
    setSplitAmong(isSingleMember ? (all[0] ? [all[0]] : []) : all);
  };

  // Keep form state in sync with members changes and enforce single-member auto-selection
  useEffect(() => {
    // Ensure payer is valid
    if (!all.includes(paidBy)) {
      setPaidBy(all[0] ?? '');
    }
    // Sanitize splitAmong to existing members
    setSplitAmong(prev => {
      const filtered = prev.filter(n => all.includes(n));
      if (isSingleMember) {
        return all[0] ? [all[0]] : [];
      }
      return filtered.length > 0 ? filtered : all;
    });
  }, [all, isSingleMember]);

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    const amt = Number(amount);
    if (!description.trim()) return;
    if (!amt || amt <= 0) return;
    if (!paidBy) return;
    const validSplit = splitAmong.filter(name => all.includes(name));
    if (validSplit.length === 0) return;

    onAdd({ description: description.trim(), amount: amt, currency, paidBy, splitAmong: validSplit });
    reset();
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-md">
      <h3 className="text-lg font-semibold text-slate-700 mb-4">Add Expense</h3>
      <form onSubmit={submit} className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm text-slate-600 mb-1">Description</label>
            <input
              type="text"
              value={description}
              onChange={e => setDescription(e.target.value)}
              placeholder="e.g. Dinner at Udon"
              className="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
              required
            />
          </div>
          <div className="grid grid-cols-3 gap-2 items-end">
            <div className="col-span-2">
              <label className="block text-sm text-slate-600 mb-1">Amount</label>
              <input
                type="number"
                inputMode="decimal"
                step="0.01"
                min="0"
                value={amount}
                onChange={e => setAmount(e.target.value)}
                className="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
                required
              />
            </div>
            <div>
              <label className="block text-sm text-slate-600 mb-1">Currency</label>
              <select
                value={currency}
                onChange={e => setCurrency(e.target.value as Currency)}
                className="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
              >
                <option value={Currency.JPY}>JPY</option>
                <option value={Currency.SGD}>SGD</option>
              </select>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm text-slate-600 mb-1">Paid by</label>
            <select
              value={paidBy}
              onChange={e => {
                setPaidBy(e.target.value);
              }}
              className="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
              disabled={isSingleMember}
            >
              {members.map(name => (
                <option key={name} value={name}>{name}</option>
              ))}
            </select>
          </div>
          <div>
            <div className="flex items-center justify-between">
              <label className="block text-sm text-slate-600 mb-1">Split among</label>
              <div className="flex gap-2">
                <button type="button" onClick={setAllMembers} className="text-xs px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 disabled:opacity-50 disabled:cursor-not-allowed" disabled={isSingleMember}>All</button>
                <button type="button" onClick={setOnlyPayer} className="text-xs px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 disabled:opacity-50 disabled:cursor-not-allowed" disabled={isSingleMember}>Only payer</button>
              </div>
            </div>
            <div className="flex flex-wrap gap-2">
              {members.map(name => (
                <label key={name} className={`px-2 py-1 rounded border cursor-pointer ${splitAmong.includes(name) ? 'bg-sky-100 border-sky-300' : 'bg-slate-50 border-slate-200'}`}>
                  <input
                    type="checkbox"
                    className="mr-2"
                    checked={splitAmong.includes(name)}
                    onChange={() => toggleSplit(name)}
                  />
                  {name}
                </label>
              ))}
            </div>
          </div>
        </div>

        <div className="flex justify-end">
          <button type="submit" className="px-4 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded">Add Expense</button>
        </div>
      </form>
    </div>
  );
};

export default ExpenseForm;

// src/lib/components/ExpenseForm.svelte
<script lang="ts">
    import { Currency, type Expense } from "$lib/types";

    export let members: string[];
    export let onAdd: (expense: Omit<Expense, "id">) => void;

    let description = "";
    let amount = "";
    let currency = Currency.JPY;
    let paidBy = "";
    let splitAmong: string[] = [];

    $: isSingleMember = members.length === 1;

    // React to members changes or init
    $: {
        if (!members.includes(paidBy)) {
            paidBy = members[0] ?? "";
        }
    }

    // splitAmong logic
    $: {
        const filtered = splitAmong.filter((n) => members.includes(n));
        if (isSingleMember) {
            splitAmong = members[0] ? [members[0]] : [];
        } else {
            // If we lost some members but still have some, keep them.
            // If we haven't initialized splitAmong yet (empty), default to all.
            // If we filtered and result is different or empty, update.
            if (
                filtered.length === 0 &&
                members.length > 0 &&
                splitAmong.length === 0
            ) {
                splitAmong = [...members];
            } else if (filtered.length !== splitAmong.length) {
                splitAmong = filtered;
            }
        }
    }

    const toggleSplit = (name: string) => {
        if (isSingleMember) return;
        if (splitAmong.includes(name)) {
            splitAmong = splitAmong.filter((x) => x !== name);
        } else {
            splitAmong = [...splitAmong, name];
        }
    };

    const setAllMembers = () => (splitAmong = [...members]);
    const setOnlyPayer = () => (splitAmong = paidBy ? [paidBy] : []);

    const reset = () => {
        description = "";
        amount = "";
        currency = Currency.JPY;
        paidBy = members[0] ?? "";
        splitAmong = isSingleMember
            ? members[0]
                ? [members[0]]
                : []
            : [...members];
    };

    const submit = () => {
        const amt = Number(amount);
        if (!description.trim()) return;
        if (!amt || amt <= 0) return;
        if (!paidBy) return;
        const validSplit = splitAmong.filter((name) => members.includes(name));
        if (validSplit.length === 0) return;

        onAdd({
            description: description.trim(),
            amount: amt,
            currency,
            paidBy,
            splitAmong: validSplit,
        });
        reset();
    };
</script>

<div class="bg-white p-6 rounded-xl shadow-md">
    <h3 class="text-lg font-semibold text-slate-700 mb-4">Add Expense</h3>
    <form on:submit|preventDefault={submit} class="space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <label
                    for="description"
                    class="block text-sm text-slate-600 mb-1">Description</label
                >
                <input
                    id="description"
                    type="text"
                    bind:value={description}
                    placeholder="e.g. Dinner at Udon"
                    class="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
                    required
                />
            </div>
            <div class="grid grid-cols-3 gap-2 items-end">
                <div class="col-span-2">
                    <label
                        for="amount"
                        class="block text-sm text-slate-600 mb-1">Amount</label
                    >
                    <input
                        id="amount"
                        type="number"
                        inputmode="decimal"
                        step="0.01"
                        min="0"
                        bind:value={amount}
                        class="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
                        required
                    />
                </div>
                <div>
                    <label
                        for="currency"
                        class="block text-sm text-slate-600 mb-1"
                        >Currency</label
                    >
                    <select
                        id="currency"
                        bind:value={currency}
                        class="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
                    >
                        <option value={Currency.JPY}>JPY</option>
                        <option value={Currency.SGD}>SGD</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <label for="paidBy" class="block text-sm text-slate-600 mb-1"
                    >Paid by</label
                >
                <select
                    id="paidBy"
                    bind:value={paidBy}
                    class="w-full px-3 py-2 rounded border border-slate-300 focus:outline-none focus:ring focus:ring-sky-200"
                    disabled={isSingleMember}
                >
                    {#each members as name}
                        <option value={name}>{name}</option>
                    {/each}
                </select>
            </div>
            <div>
                <div class="flex items-center justify-between">
                    <span class="block text-sm text-slate-600 mb-1"
                        >Split among</span
                    >
                    <div class="flex gap-2">
                        <button
                            type="button"
                            on:click={setAllMembers}
                            class="text-xs px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={isSingleMember}>All</button
                        >
                        <button
                            type="button"
                            on:click={setOnlyPayer}
                            class="text-xs px-2 py-1 rounded bg-slate-100 hover:bg-slate-200 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={isSingleMember}>Only payer</button
                        >
                    </div>
                </div>
                <div class="flex flex-wrap gap-2">
                    {#each members as name}
                        <label
                            class={`px-2 py-1 rounded border cursor-pointer ${splitAmong.includes(name) ? "bg-sky-100 border-sky-300" : "bg-slate-50 border-slate-200"}`}
                        >
                            <input
                                type="checkbox"
                                class="mr-2"
                                checked={splitAmong.includes(name)}
                                on:change={() => toggleSplit(name)}
                            />
                            {name}
                        </label>
                    {/each}
                </div>
            </div>
        </div>

        <div class="flex justify-end">
            <button
                type="submit"
                class="px-4 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded"
                >Add Expense</button
            >
        </div>
    </form>
</div>
